TIME_OPTIONS = ['Max', '1 Year', '6 Months', 'Month', 'Week']

#colors
BG_COLOR = '#19233C'
INPUT_BG_COLOR = '#121A2C'
TICK_COLOR = '#EEEEEE'
HIGHLIGHT_COLOR = '#21EAAD'
TEXT_COLOR = '#FFFFFF'
TITLE_HEX_COLOR = 0x003c2319